{% set version = "2.5" %}
{% set build = 0 %}
{% set sha256 = "957d5df8c83c29a687a7bb64c46dfa7861916adc2c6eb4bf9bda51e1fac80050" %}

package:
  name: tmux
  version: {{ version }}

source:
  url: https://github.com/tmux/tmux/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - autoconf
    - automake
    - libtool
    - m4
    - pkg-config
    - libevent 2.0.22
    - ncurses 5.9

  run:
    - libevent 2.0.22
    - ncurses 5.9

test:
  commands:
    # Verify command existence.
    - which tmux

    # Check that no server is running.
    - $(tmux info || true) 2> >(grep "no server running on")

about:
  home: https://tmux.github.io/
  license: ISC
  license_file: COPYING
  summary: A terminal multiplexer.

extra:
  recipe-maintainers:
    - jakirkham
    - dougalsutherland
