{% set version = "3.3a" %}
{% set sha256 = "e4fd347843bd0772c4f48d6dde625b0b109b7a380ff15db21e97c11a4dcdf93f" %}
{% set build_number = "0" %}

package:
  name: tmux
  version: {{ version }}

source:
  url: https://github.com/tmux/tmux/releases/download/{{ version }}/tmux-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - m4
    - make
    - pkg-config

  host:
    - libevent
    - libutf8proc  # [osx]
    - ncurses

  run:
    - libevent
    - ncurses
    - libutf8proc  # [osx]

test:
  commands:
    # Verify command existence.
    - which tmux

    # Check that no server is running.
    - $(tmux info || true) 2> >(grep "no server running on")  # [not osx]
    - (tmux info 2>&1 || true) | grep -e "no server running on"  # [osx]
about:
  home: https://tmux.github.io/
  license: ISC
  license_family: OTHER
  license_file: COPYING
  summary: A terminal multiplexer.
  dev_url: https://github.com/tmux/tmux
  doc_url: https://github.com/tmux/tmux

extra:
  recipe-maintainers:
    - jakirkham
    - djsutherland
