{% set version = "2.7" %}
{% set sha256 = "9ded7d100313f6bc5a87404a4048b3745d61f2332f99ec1400a7c4ed9485d452" %}

package:
  name: tmux
  version: {{ version }}

source:
  url: https://github.com/tmux/tmux/releases/download/{{ version }}/tmux-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - m4
    - pkg-config

  host:
    - libevent
    - ncurses

  run:
    - libevent
    - ncurses

test:
  commands:
    # Verify command existence.
    - which tmux

    # Check that no server is running.
    - $(tmux info || true) 2> >(grep "no server running on")

about:
  home: https://tmux.github.io/
  license: ISC
  license_file: COPYING
  summary: A terminal multiplexer.

extra:
  recipe-maintainers:
    - jakirkham
    - dougalsutherland
