{% set version = "2.7" %}
{% set sha256 = "fbfede3d8af83d62f5d285a91214297c2bc90e7167bac79ffa10650fcbb640f9" %}

package:
  name: tmux
  version: {{ version }}

source:
  url: https://github.com/tmux/tmux/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - pkg-config
    - {{ compiler('c') }}
  host:
    - m4
    - libevent
    - ncurses

  run:
    - libevent
    - ncurses

test:
  commands:
    # Verify command existence.
    - which tmux

    # Check that no server is running.
    - $(tmux info || true) 2> >(grep "no server running on")

about:
  home: https://tmux.github.io/
  license: ISC
  license_file: COPYING
  summary: A terminal multiplexer.

extra:
  recipe-maintainers:
    - jakirkham
    - dougalsutherland
