travis:
  secure:
    BINSTAR_TOKEN: D35dbk+GFXyOG7XGvUDbhdLNXbarCBoyVOHluR7YTn1R9tG8CKPjlRnkUhNknlm8t0uCDhnttLEm8y1EjlbH/R7b5IT5sx7vYOw7h7KUekGecVdrVHPtxMn16APaMhBulbuD88I0u+CMb2lnNW5mPf35BqBRfSia3GTWcsCRW+b90SHl8DG+/KL1rdTWRVIIrHycgzhiAl8TR/xT473MHuzPka7A1t7pjApSW4IljwDGe3tK71KtWxL1W8+pH5f7xBQK7DIh6XnMo2bnV8qbOrIK4u9FZTMQPQem4v1Gj5coawjXpnz4qSn9ZTjUdQAcls59k9WThGYb7QG69b4gA07bbWCA/ed9KG8nybu00g2y92HxPS5X+gT9y+/RrCRikB+EKeCbI7MY7iJs9YHSmVJrzRoTA35aeZtiYkqWyTDhO+MRtRqRrlwCFNA+nasuWAz/h8w4whSvdVQ6KStHqq6qEqsKVu1z4KEj2WP3J2TkvKmPm7goPXUGFmak1qzQvti7Bi/8gvPdB380qMiAtw6e7tQgaSgmf8eDf4TsQAfQUcntpubtBNROlTVnia8GASqX6rdm9PQUbIAnq0HdqY7QcUsNDWZOoB0UYs+Jg8hG6zLm4WMLfmHseGZRUBdpvPnCXCDV2Xm1n97woEfuJxqWhMu+xLDxfC4XbMwT//k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
