travis:
  secure:
    BINSTAR_TOKEN: SFXxLiVu0wQooFB6oVBRy8k0X6G3EGzr6e7j4sZfHuf7nGXqieEKkHXNfHDv9HAkhCuTFKOIPqkQZo7H7DRbISuu6EfGXw3eLrT5iYbqTsClFz9HYFE5AMAO5VsrHty/LHy9D4JRiTi6XlmHldeXFSLawPsR6Yo2lb/iWXsAxWV0+ZPU+AY79BKSXUWtCmuo6jKs7ta7hpiF6KgSZEkz1k/ZcIsmdoH0LX4oQOf+z+vJJ0/msV72iLhkc3vZPFTz78l1+fSGNjRjIsIVgAqokaIE7XHlJ472Dn0nBtYcWUdGA9W9TksXZW+KPnRERVYaqh7iCCpZ2NXgPk6M+2XRRlfI6AxndaMCcepAI39sDt89ib7PPZ97UhMymTjb/WW6NNXy4+LCpL6sv8J/uQCoW2qvB4BwC1D3GHkVXCz2FaSd2nyH6VLpl8S+4CCOFwbDRnoUTZTz+jLNBzXU8DKA/kAcC9Dcw5QooccYXQikQ75TravEcWU9Fx4VMLjLhIqYQLyz4U2xGl0AjIGO7F6btPpktYZaNiAs/fXSxmrKmhqleMzLAS9VSSaY48JmEklfylwzE8S1P3DQ1S5M9bOr24HJGXRotGIG2vvSA2+UyhfutRNolePNTB9Ym8mUMWjUdcocQ6KRmYNpE98T2gESddaNYvgH2cOjRBDy54ti0iI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
