travis:
  secure:
    BINSTAR_TOKEN: hCbEnx1sntndH1PkJnhkE85zcmVgSaYUV6cfU93CezRDim9/R8M3e4NzHtYGFgHnPOIUVNSA34Zd6IljO8MLiqNU/ukoR+u4R9AloE2pRZ9eDQ11HBPFnNMc6yOhEjAAvqb4kGf53ZKjAkI3UEU7e8QGWX0Qfdom/CpIO5aGEcQHHuAGn1JgLNTrZbIiwQ02y+i0yk+FqwHWF88tEbQwfCreMZo6UlBEHC/ID39XqEjv0P8kuoi4ssBfNuSngrzVUxPVTx6UhGJmON4n4zMIx74PD8+ApYZ0XGd8nekqg6rDUne5e1keznTNsDPML+pYh6P68io+oOPfPaG3F/uhgUKR21ACCdG+OP/FmyA/1hzuflqUEceWg+Zk/qMP0HJYnZiEc6mDz90bQtN2c0W16J9BAmaszPpPbWG1JTcPAG7L8Dd3u1GIq308KcUNJ1KOcqf58Uf0CBY6avgIP/gpKhe6wYuYhOzoZEFp9UTlwKglnwQFoLenKx8U1Dj7LWxLS8E0M0jbJYYWZJjnMvj2Q0pcMp28oqokNP105rVztyGQBeocPVoXOOdO+XIeIp+QZvheuCozFlNAWHL7gT/XifsosyBliVt8jQA/572qWWoL2EMl8KVHvi8taRipNoPjvlbGuzJLReNEA8hg7d9OXiS7vLXfKnyO767VnYLfem0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
