travis:
  secure:
    BINSTAR_TOKEN: q+LhrIHYq9PAUZ2uEnUhTMDZdHfntqHCvTKLZCru/9ZPgrlrRMRXVKD70cmaifrsQXvf2D58p/eyY3y+VzCq/WxIepVAtqVDMqDXE9v+Afnf95jEJm4WS6xbXCY/5EPAKbhgmEbmTs0im7ZeV9Z2Sh/LwXHe6EPZ60VHAmyDy6p9t/U/MhZddCk8xCUgVIgZ+F9E021xqAJGsfYDrnTHi3HVjnxzMRhw/cKWrda7QCi/B8z1yFzDcwSi5asxDJlAWPEB+i9i9ZgauoTFopWRndLCFLqn5Sp7Gj5x9cO9bAXrlyVUSmUT01nsueoJHUwFBS2T3U934dLnNXMqsgDEqpVL15Z96VFJQDGpBakypgaelxdMD/StfP39RNDRl9Hcqq4y0LSFOU8UwaFpuICiyVP5C/rjhC1N+40hb11kzLtphpbVhPz3rJUwtLu6pUolgogvaZed61f/o1YdgF+wRVmC2WuT5wQv5j59oDPmP3HnhM5lbYAvJ+qNSfDd3cPK0t2i0BldFt3Qbg8+ju85q2hO52D1qEqNeFQwQH5lda7WXO3awVeuVuHRBc0qhKq6uSmnBm5otelBo/MP7b3q98GlbWUiWYCC38UgY28nwwT5EY43qCp8rTHKIcl3SnFIqQR3FdXdAUi7AKd4C5DM9XGBGlgk4XmJPkM+7vzi0F0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
