travis:
  secure:
    BINSTAR_TOKEN: n+PkXeKmfO3qve4PKT8+ho0I2jU/HBKdZ0LcYFWigiy5jWP3OQ6mywqbHV76lJiKgp8ErZrDXdkg0DZGNtpQl/0KqiaMfPpgSQbxvyd8Rt9eRfpHLW1o9Rz90KBbt0c7l0xmUhGMPfITYKQSckjqJFtb1rH44ATeyLFHzBIOGKPUK1EQGWywWDazKpL7/FAYja61cgnNyr1Qk6PfXblorPU+k9MKHKj/VCvr5DT1YkMPOMQvv3GZdfBJRm5QUCEcqg6QlsY7FxKf+M+9O4tgibeYLgrII5J8lbS9ZLgskXUeNEXsri4m7HKIvQ06+VfHHw+RNsp+vItZq1PcjOj8PavhOdAqZ89wHO8P+4pGCnuXAqvDqc6kkiKWpBrSQPwX91ulFno/QERZRVJfzDMoAfOhS/LKwnT3rpkbPbJld07IQhfvCUt2s1ljpQqTeG/MobSsnncHY+kZHlLVWAV0uxNLRXq4Ude4RRtFC/ZSPcttVLocA6tjQzvYdmALnNi9iXWOZXHTJGvx7veJ6ZTcV3WGxHym2F1FR4bAJkYl06Mxiqn2mLO3501SARhAYdKnbhQKOkyA+FXr7+bjpsddvQyk8KC4pLAuzRARgTqBK4PJqI5k52XmkgVZUrBwfgauPURzsoEU687i2aeaCCVF8zsV7zZgDdhKk8nhITgZg9U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
